{{- range $secretType, $secretData := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretType }}
type: Opaque
stringData:
  {{- range $secretKey, $secretValue := $secretData }}
  {{ $secretType | upper }}_{{ $secretKey | upper }}: {{ $secretValue }}
  {{- end }}
{{- end }}