{{- $workflowTemplate := "workflow-template" }}
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: {{ include "ml-workflow.fullname" . }}
spec:
  entrypoint: ml-workflow
  templates:
  - name: ml-workflow
    steps:
  {{- range .Values.workflow_files }}
    - - name: {{ . | replace ".py" "" }}
        template: {{ $workflowTemplate }}
        arguments:
          parameters: [{name: file, value: {{ . }}}]
  {{- end }}
  - name: {{ $workflowTemplate }}
    inputs:
      parameters:
        - name: file
    container:
      image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
      args: [{{`"{{inputs.parameters.file}}"`}}]
      envFrom:
      {{- range $secretType, $secretData := $.Values.secrets }}
      - secretRef:
          name: {{ $secretType }}
      {{- end }}      
      # TODO : move this duplicate in template
      {{- range $_, $key := (tuple "imagePullPolicy" "resources" "podSecurityContext" ) }}
      {{- $parameter := index $.Values $key }}
      {{- if $parameter }}
      {{ $key }} : {{ index $.Values $key }}
      {{- end }}
      {{- end }}
    {{- range $_, $key := (tuple "nodeSelector" "securityContext" "tolerations" "affinity") }}
    {{- $parameter := index $.Values $key }}
    {{- if $parameter }}
    {{ $key }} : {{ index $.Values $key }}
    {{- end }}
    {{- end }}
